# Generated by Django 2.1.1 on 2018-09-19 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='alt_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
