# Generated by Django 2.1.1 on 2018-09-19 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_userprofile_alt_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='alt_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='current_ctc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='expected_ctc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='experience',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='summary',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
